// utils/wilayas.js

const WILAYAS = Object.freeze([
  { code: "01", name: "Adrar" },
  { code: "16", name: "Alger" },
  { code: "23", name: "Annaba" },
  { code: "44", name: "Aïn Defla" },
  { code: "40", name: "Aïn Témouchent" },
  { code: "05", name: "Batna" },
  { code: "07", name: "Biskra" },
  { code: "09", name: "Blida" },
  { code: "34", name: "Bordj Badji Mokhtar" },
  { code: "10", name: "Bouira" },
  { code: "35", name: "Boumerdès" },
  { code: "08", name: "Béchar" },
  { code: "06", name: "Béjaïa" },
  { code: "46", name: "Béni Abbès" },
  { code: "02", name: "Chlef" },
  { code: "25", name: "Constantine" },
  { code: "17", name: "Djelfa" },
  { code: "32", name: "El Bayadh" },
  { code: "39", name: "El M'Ghair" },
  { code: "36", name: "El Meniaa" },
  { code: "47", name: "El Meghaier" },
  { code: "48", name: "El Meniâa" },
  { code: "12", name: "El Oued" },
  { code: "31", name: "El Tarf" },
  { code: "30", name: "Ghardaïa" },
  { code: "24", name: "Guelma" },
  { code: "33", name: "Illizi" },
  { code: "18", name: "Jijel" },
  { code: "56", name: "In Guezzam" },
  { code: "55", name: "In Salah" },
  { code: "41", name: "Khenchela" },
  { code: "43", name: "Mila" },
  { code: "27", name: "Mostaganem" },
  { code: "28", name: "M'Sila" },
  { code: "29", name: "Mascara" },
  { code: "26", name: "Médéa" },
  { code: "45", name: "Naâma" },
  { code: "57", name: "Ouled Djellal" },
  { code: "04", name: "Oum El Bouaghi" },
  { code: "48", name: "Relizane" },
  { code: "20", name: "Saïda" },
  { code: "19", name: "Sétif" },
  { code: "21", name: "Skikda" },
  { code: "11", name: "Tamanrasset" },
  { code: "14", name: "Tiaret" },
  { code: "37", name: "Timimoun" },
  { code: "42", name: "Tipasa" },
  { code: "38", name: "Tissemsilt" },
  { code: "15", name: "Tizi Ouzou" },
  { code: "13", name: "Tlemcen" },
  { code: "49", name: "Touggourt" },
  { code: "51", name: "Ouargla" },
  { code: "50", name: "Djanet" },
  { code: "54", name: "Bordj Baji Mokhtar" },
  { code: "52", name: "Béni Abbès" },
  { code: "53", name: "Timiaouine" }
]);

module.exports = {
  WILAYAS,
  WILAYA_CODES: WILAYAS.map(w => w.code),
};
